services:

  apache:
    restart: always
    image: reannz/admintool_apache:latest
    container_name: apache
    environment:
        DJNRO_HOST: djnro
        HTTPS_PORT: 443
        HTTPD_ARGS: ""
        #HTTPD_ARGS: -DAPACHE_LOGS_STDOUT
    env_file:
        - admintool.env
        - global-env.env
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - apache-certs:/usr/local/apache2/conf/external
        - apache-logs:/usr/local/apache2/logs
    links:
        - "djnro:djnro"

  djnro:
    restart: always
    #build: ./djnro/
    image: reannz/admintool_djnro:latest
    container_name: djnro
    #log_driver: syslog
    environment:
        DB_HOST: postgres
    env_file:
        - admintool.env
        - global-env.env
    volumes:
        - djnro-data:/djnro/data
    links:
        - "postgres:postgres"

  # djnro-cron periodically fetching upstream all.kml
  djnro-scheduler:
    restart: always
    image: reannz/admintool_djnro:latest
    container_name: djnro-scheduler
    environment:
        DB_HOST: postgres
        KML_REFRESH_INTERVAL: 3600
    env_file:
        - admintool.env
        - global-env.env
    volumes:
        # shared data dir for the all.kml file
        - djnro-data:/djnro/data
    command: ./run-kml-refresh.sh

  postgres:
    restart: always
    container_name: postgres
    image: reannz/admintool_postgres:latest
    env_file:
        - admintool.env
        - global-env.env
    volumes:
        - postgres-data:/var/lib/postgresql/data

#  filebeat:
#    restart: always
#    image: reannz/admintool_filebeat:latest
#    container_name: filebeat
#    env_file:
#        - admintool.env
#        - global-env.env
#    volumes:
#        - filebeat-registry:/var/lib/filebeat
#        # get access to Apache logs
#        - apache-logs:/usr/local/apache2/logs

volumes:
  # all volume names will get prefixed with the project name - "admintool_"
  apache-certs: {}
  apache-logs: {}
  djnro-data: {}
  postgres-data: {}
  filebeat-registry: {}
